CleverCase/ember-bootstrap-controls

addon/components/bootstrap-input.js
addon/components/bootstrap-textarea.js
addon/mixins/components/inputable.js
addon/templates/components/bootstrap-textarea.hbs
app/components/bootstrap-textarea.js
package.json
tests/unit/components/bootstrap-textarea-test.js

@jweakley and @grelement please review.

Initial version

---

README.md
addon/components/bootstrap-input.js
addon/templates/components/bootstrap-input.hbs

added documentation and custom css for labels. fixes #7.

---

addon/templates/components/bootstrap-selectize.hbs

We will need to do a version bump if this is accepted.

Selectize ids

---

README.md

Just added a small explanation of the textarea helper.

added example of textarea use.

---

README.md

Updated README further to include explanations of all controls (as far as I know at this point)

Updated README.md (again)

---

README.md
addon/components/bootstrap-power-select.js
addon/components/bootstrap-selectize.js
addon/templates/components/bootstrap-power-select.hbs
app/components/bootstrap-power-select.js
blueprints/ember-bootstrap-controls/index.js
package.json
tests/dummy/app/styles/app.scss

We will also need to do a version bump and upgrade notes once this is approved.

Power select

---

README.md
addon/components/bootstrap-pagination-nav.js
addon/helpers/add-numbers.js
addon/helpers/minus-numbers.js
addon/mixins/routes/pagination.js
addon/mixins/routes/sorted.js
addon/routes/pagination.js
addon/routes/sorted.js
addon/templates/components/bootstrap-pagination-nav.hbs
app/components/bootstrap-pagination-nav.js
app/helpers/add-numbers.js
app/helpers/minus-numbers.js

This will need a version bump on release.

Pagination

---

addon/components/bootstrap-power-select.js
addon/mixins/routes/pagination.js
addon/templates/components/bootstrap-power-select.hbs

This will need a version bump.

Loading Improvements

---

README.md
addon/components/bootstrap-power-select.js
addon/templates/components/bootstrap-power-select.hbs

Custom matcher

---

addon/components/bootstrap-date-picker.js
addon/components/bootstrap-debounce-input.js
addon/components/bootstrap-input.js
addon/components/bootstrap-multi-select.js
addon/components/bootstrap-power-select.js
addon/components/bootstrap-textarea.js
addon/templates/components/bootstrap-date-picker.hbs
addon/templates/components/bootstrap-debounce-input.hbs
addon/templates/components/bootstrap-input.hbs
addon/templates/components/bootstrap-multi-select.hbs
addon/templates/components/bootstrap-power-select.hbs
addon/templates/components/bootstrap-textarea.hbs
package.json

- Required attribute which adds the `required` class.
- Cleans up the tags
- Removed column

Added required

---

README.md
addon/components/bootstrap-checkbox-button.js
addon/components/bootstrap-checkbox-group.js
addon/components/bootstrap-radio-button.js
addon/components/bootstrap-radio-group.js
addon/templates/components/bootstrap-checkbox-button.hbs
addon/templates/components/bootstrap-checkbox-group.hbs
addon/templates/components/bootstrap-radio-button.hbs
addon/templates/components/bootstrap-radio-group.hbs
app/components/bootstrap-checkbox-button.js
app/components/bootstrap-checkbox-group.js
app/components/bootstrap-radio-button.js
app/components/bootstrap-radio-group.js
package.json
tests/integration/components/bootstrap-checkbox-button-test.js
tests/integration/components/bootstrap-checkbox-group-test.js
tests/integration/components/bootstrap-radio-button-test.js
tests/integration/components/bootstrap-radio-group-test.js

- Checkbox group support.
- Radio group support.

Radio and checkbox groups

---

addon/components/bootstrap-input.js
addon/templates/components/bootstrap-checkbox-button.hbs
addon/templates/components/bootstrap-checkbox-group.hbs
addon/templates/components/bootstrap-date-picker.hbs
addon/templates/components/bootstrap-debounce-input.hbs
addon/templates/components/bootstrap-input.hbs
addon/templates/components/bootstrap-multi-select.hbs
addon/templates/components/bootstrap-power-select.hbs
addon/templates/components/bootstrap-textarea.hbs
blueprints/ember-bootstrap-controls/index.js
package.json

Hopefully this gets rid of the ugly red box around required input divs! Please review.

Ember input required styling

---

addon/components/bootstrap-input.js
addon/templates/components/bootstrap-input.hbs
package.json

added key-up and key-down event functionality to text inputs

Expand Key Event Options

---

README.md
addon/components/bootstrap-power-select.js
addon/templates/components/bootstrap-power-select.hbs

Fixes #59 
Added srOnly attribute to the power-select control

Add sr only to power select

---

README.md

Add upgrade instructions and remove wildland specific `app-ember` folder information.

Upgrade instructions

---

addon/components/bootstrap-checkbox-group.js
addon/components/bootstrap-currency-input.js
addon/components/bootstrap-date-picker.js
addon/components/bootstrap-debounce-input.js
addon/components/bootstrap-input.js
addon/components/bootstrap-multi-select.js
addon/components/bootstrap-power-select.js
addon/components/bootstrap-radio-group.js
addon/components/bootstrap-textarea.js
addon/templates/components/bootstrap-checkbox-group.hbs
addon/templates/components/bootstrap-currency-input.hbs
addon/templates/components/bootstrap-date-picker.hbs
addon/templates/components/bootstrap-debounce-input.hbs
addon/templates/components/bootstrap-input.hbs
addon/templates/components/bootstrap-multi-select.hbs
addon/templates/components/bootstrap-power-select.hbs
addon/templates/components/bootstrap-radio-group.hbs
addon/templates/components/bootstrap-textarea.hbs

Added `classNames` to components with tagName set to empty string in controller.
The tagName not being set was not putting the class attr into the components.
This was causing an issue with Unibest.

Add ClassNames To Components

---

README.md
addon/components/bootstrap-checkbox.js
addon/components/freestyle/bootstrap-checkbox.js
addon/templates/components/bootstrap-checkbox.hbs
addon/templates/components/ember-bootstrap-controls-freestyle.hbs
addon/templates/components/freestyle/bootstrap-checkbox-button.hbs
addon/templates/components/freestyle/bootstrap-checkbox.hbs
app/components/bootstrap-checkbox.js
app/components/freestyle/bootstrap-checkbox.js

Fixes #32 
Added a bootstrap-checkbox component.
Also Fixes #19 and Fixes #6

Issue 32 bootstrap checkbox

---

README.md
addon/components/bootstrap-power-select.js
addon/components/freestyle/bootstrap-power-select.js
addon/templates/components/ember-bootstrap-controls-freestyle.hbs
addon/templates/components/freestyle/bootstrap-power-select.hbs
app/components/freestyle/bootstrap-power-select.js
package.json

Updated power-select for freestyle guide
Fixed the searchEnabled property, can still set to true without specify a searchField, but default s to false.

Added ember-freestyle component for ember-power-select

---

README.md
addon/components/bootstrap-debounce-input.js
addon/components/freestyle/bootstrap-debounce-input.js
addon/mixins/components/inputable.js
addon/templates/components/bootstrap-debounce-input.hbs
addon/templates/components/ember-bootstrap-controls-freestyle.hbs
addon/templates/components/freestyle/bootstrap-debounce-input.hbs
app/components/freestyle/bootstrap-debounce-input.js
package.json

Uses ember concurrency instead of observer.
Fixed #64

Use Ember Concurrancy

---

README.md
addon/components/bootstrap-checkbox.js
addon/components/freestyle/bootstrap-checkbox.js
addon/templates/components/bootstrap-checkbox.hbs
addon/templates/components/freestyle/bootstrap-checkbox.hbs
package.json

Removed readonly and value from checkbox

---

README.md
addon/components/bootstrap-mask-input.js
addon/components/freestyle/bootstrap-mask-input.js
addon/templates/components/bootstrap-mask-input.hbs
addon/templates/components/ember-bootstrap-controls-freestyle.hbs
addon/templates/components/freestyle/bootstrap-mask-input.hbs
app/components/bootstrap-mask-input.js
app/components/freestyle/bootstrap-mask-input.js
tests/integration/components/bootstrap-mask-input-test.js

This adds the Text-Masking helper to the library.

added text mask helper for inputs

---

package.json

changed from 0.12.0 to 0.13.0 after recent changes.

minor version bump

---

README.md
addon/components/bootstrap-multi-select-lazy.js
addon/components/bootstrap-multi-select.js
addon/components/freestyle/bootstrap-power-select-lazy.js
addon/templates/components/bootstrap-multi-select-lazy.hbs
addon/templates/components/bootstrap-multi-select.hbs
addon/templates/components/freestyle/bootstrap-power-select-lazy.hbs
addon/templates/components/power-select/lazy-options.hbs
addon/utils/lazy-select-state.js
app/components/bootstrap-multi-select-lazy.js
package-lock.json
tests/integration/components/bootstrap-multi-select-lazy-test.js

This PR adds a lazy multi select to the control library and abstracts
out the lazy-select state so that the majority of the code between the
two components an be re-used simply.

Add lazy multi-select

---

addon/templates/components/bootstrap-date-picker.hbs
addon/templates/components/bootstrap-input.hbs
addon/templates/components/bootstrap-mask-input.hbs
addon/templates/components/bootstrap-multi-select-lazy.hbs
addon/templates/components/bootstrap-power-select-lazy.hbs

Mirror of https://github.com/wildland/ember-bootstrap-controls/pull/103, but into v0.x-stable

Add disabled to text mask

---

addon/templates/components/bootstrap-date-picker.hbs

Fixes a regression of the `changeDate` action accidentally disappearing.

added back changeDate event to date picker

---

addon/templates/components/bootstrap/control-wrapper.hbs

Updates to use the new v4 classes

Use invalid-feedback

---

addon/components/bootstrap-multi-select.js
addon/components/bootstrap/-label.js
addon/templates/components/bootstrap-input.hbs
addon/templates/components/bootstrap-multi-select-lazy.hbs
addon/templates/components/bootstrap-multi-select.hbs
addon/templates/components/bootstrap-power-select-lazy.hbs
addon/templates/components/bootstrap-power-select.hbs
addon/templates/components/bootstrap/-label.hbs
addon/templates/components/bootstrap/control-wrapper.hbs

This fixes the label on `ember-power-select`. When viewing the deployed documentation app, you should now see the label "Name".

Fix label on power select

---

addon/templates/components/bootstrap-multi-select-lazy.hbs
addon/templates/components/bootstrap-multi-select.hbs
addon/templates/components/bootstrap-power-select-lazy.hbs
addon/templates/components/bootstrap-power-select.hbs

Removed duplicate `allowClear`.

Fixes #117

---

addon/components/bootstrap/-input.js
addon/templates/components/bootstrap-input.hbs
package-lock.json

Fixes some of the events on input for 0.x-stable

fix enter and focus-out events on input

---

README.md

Update readme for edge case

---

CHANGELOG.md
addon/mixins/routes/pagination.js
addon/templates/components/freestyle/bootstrap-pagination-nav.hbs
package.json

(Description in grammatically correct, complete sentences)

Improved pagination support.

---

CHANGELOG.md
addon/components/bootstrap-button.js
addon/templates/components/bootstrap-button.hbs

(Description in grammatically correct, complete sentences)

Updated button with drop.

---

addon/components/bootstrap/radio-group.js
addon/templates/components/bootstrap/-label.hbs
addon/templates/components/bootstrap/radio-group.hbs
addon/templates/components/freestyle/bootstrap/radio-group.hbs
package.json

This added index and a few other convenience variables to radio-group.

Radio group enhancements

---

CHANGELOG.md
addon/components/bootstrap-inputs/-select.js
addon/components/bootstrap/simple-select.js
addon/components/freestyle/bootstrap/simple-select.js
addon/templates/components/bootstrap-inputs/-select.hbs
addon/templates/components/bootstrap/simple-select.hbs
addon/templates/components/ember-bootstrap-controls-freestyle.hbs
addon/templates/components/freestyle/bootstrap/simple-select.hbs
app/components/bootstrap-inputs/-select.js
app/components/bootstrap/simple-select.js
app/components/freestyle/bootstrap/simple-select.js
package-lock.json
package.json
tests/integration/components/bootstrap-inputs/-select-test.js
tests/integration/components/bootstrap/simple-select-test.js

This PR adds a simple native HTML select as an alternative to power select.

Added simple select

---

package.json

Using the new ember-bootstrap-datepicker

Test ember bootstrap datepicker wl repo

---

addon/templates/components/bootstrap-date-picker.hbs
package-lock.json
package.json

Adds a disabled attribute to the date picker so that it can be disabled.

Add disabled to date picker

---

CHANGELOG.md
addon/components/bootstrap-inputs/-date.js
addon/components/freestyle-prop-types.js
addon/components/freestyle-prop-types/-date.js
addon/components/freestyle/bootstrap-inputs/-date.js
addon/templates/components/bootstrap-inputs/-date.hbs
addon/templates/components/ember-bootstrap-controls-freestyle.hbs
addon/templates/components/freestyle-prop-types/-date.hbs
addon/templates/components/freestyle-prop-types/-one-of.hbs
addon/templates/components/freestyle/bootstrap-inputs/-date.hbs
app/components/bootstrap-inputs/-date.js
app/components/freestyle-prop-types/-date.js
app/components/freestyle/bootstrap-inputs/-date.js
tests/integration/components/bootstrap-inputs/-date-test.js
tests/integration/components/freestyle-prop-types/-date-test.js

Implemented new date control component. Completes #151

Issue 151 - Date control

---

CONTRIBUTING.md
addon/components/bootstrap-button.js
addon/components/bootstrap-inputs/-select.js
addon/components/freestyle/bootstrap-inputs/-text.js
addon/components/freestyle/bootstrap/radio-group.js
addon/templates/components/bootstrap-inputs/-select.hbs
addon/templates/components/ember-bootstrap-controls-freestyle.hbs
addon/templates/components/freestyle/bootstrap-inputs/-date.hbs
addon/templates/components/freestyle/bootstrap-inputs/-number.hbs
addon/templates/components/freestyle/bootstrap-inputs/-password.hbs
addon/templates/components/freestyle/bootstrap-inputs/-text.hbs
addon/templates/components/freestyle/bootstrap/radio-group.hbs
addon/templates/components/freestyle/bootstrap/simple-select.hbs

This adds better freestyle documentation and separates the components better.

Freestyle documentation updates

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE

Fixes #209
Added code owner and issue template files
this adds two new files to add a template for user to create new issue and to default the code owners.

Added Github Template Files

---

addon/templates/components/bootstrap-multi-select-lazy.hbs
addon/templates/components/bootstrap-multi-select.hbs
addon/templates/components/bootstrap-power-select-lazy.hbs
addon/templates/components/bootstrap-power-select.hbs
package-lock.json
package.json

V0.x bug fix

---

CHANGELOG.md
package-lock.json
package.json

This is a publish/version bump of the library.

Version bump.

---

CHANGELOG.md
package-lock.json
package.json

We are taking this out of beta!

1.0.0 release

---

addon/templates/components/freestyle-prop-types.hbs

This work formats prop type documentation for advanced usage in a more readable and usable format.

Formatting prop type documentation

---

app/styles/app.scss
package-lock.json
package.json

This corrects an issue with the dependencies.

Updated dependencies.

---

CHANGELOG.md
addon/components/bootstrap/buttons/-button.js
package-lock.json
package.json
tests/integration/components/bootstrap/buttons/-button-test.js

Fixed a bug where buttons were not able to be disabled.

Minor fix.

---

addon/components/modals/header/-close-button.js
package-lock.json
package.json

The button was blank and now has the correct layout.

Minor close button fix.

---

addon/templates/components/bootstrap/simple-form/-controls.hbs

added submit action
As a developer, I want a submit action so that I can have a custom button.

added submit action to simple form

---

CHANGELOG.md
addon/components/modals/ember-model.js
addon/templates/components/modals/-form.hbs
addon/templates/components/modals/-modal.hbs
addon/templates/components/modals/ember-model.hbs
package-lock.json
package.json
tests/integration/components/bootstrap-inputs/markdown-test.js
tests/integration/components/bootstrap-pagination-nav/page-item-test.js
tests/integration/components/bootstrap-pagination-nav/page-link-test.js

This adds a modal `onHidden` fix and publish of 1.1.0.

1.1.0 branch

---

addon/components/bootstrap-form.js
addon/components/bootstrap-inputs/markdown.js
addon/components/bootstrap/-form-controls/save-button.js
addon/components/bootstrap/buttons/accept-button.js
addon/components/bootstrap/edit-form.js
addon/components/bootstrap/form/-controls.js
addon/components/freestyle/bootstrap-checkbox.js
addon/components/freestyle/bootstrap-input.js
addon/components/freestyle/modals/ember-model.js
addon/components/modals/ember-model.js
addon/templates/components/bootstrap/simple-form/-controls.hbs
addon/templates/components/ember-bootstrap-controls-freestyle.hbs
index.js
package.json
tests/dummy/app/templates/freestyle.hbs

As a Developer I want an easier way to navigate documentation of controls.

Start of New Freestyle Structure and Accept Button is changed to color success

---

CHANGELOG.md
README.md
addon/components/bootstrap-currency-input.js
addon/components/bootstrap-mask-input.js
addon/components/bootstrap-phone-mask-input.js
addon/components/freestyle/bootstrap-currency-input.js
addon/components/freestyle/bootstrap-mask-input.js
addon/templates/components/bootstrap-currency-input.hbs
addon/templates/components/bootstrap-mask-input.hbs
addon/templates/components/bootstrap-phone-mask-input.hbs
addon/templates/components/ember-bootstrap-controls-freestyle.hbs
addon/templates/components/freestyle/bootstrap-currency-input.hbs
addon/templates/components/freestyle/bootstrap-mask-input.hbs
app/components/freestyle/bootstrap-currency-input.js
package-lock.json
package.json

Updated the input mask components to use ember-inputmask. 
Update the currency input to use the same library
Added both components to freestyle
[ember-inputmask](https://github.com/brandynbennett/ember-inputmask)

Update Input mask library

---

addon/components/bootstrap-currency-input.js
addon/components/bootstrap-mask-input.js
addon/components/bootstrap-phone-mask-input.js
addon/templates/components/bootstrap-phone-mask-input.hbs
package-lock.json
package.json

Set the value passed in to the inputs to be the masked.

Update input mask values

---

CHANGELOG.md
addon/mixins/routes/sorted.js
package-lock.json
package.json

This fixes a bug where the initial sort of the route mixin was doing the opposite of the route reset. This was causing the mixin to have the opposite sorting order if a user navigated away and then came back.

Sorting bug fix

---

addon/templates/components/bootstrap-multi-select-lazy.hbs
addon/templates/components/bootstrap-multi-select.hbs
package-lock.json
package.json

Added a passthrough variable for verticalPosition.

Vertical Position
